name: stac
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - rasterio=1.4.3
  - pystac=1.13.0
  - pandas=2.3.1
  - shapely=2.1.1
  - pip:
      - rio-stac==0.10.1
      - rio-cogeo==5.4.2
      - stac-validator==3.10.0
      - tqdm

